services:
  web:
    build: .
    container_name: inventory_backend
    command: daphne -b 0.0.0.0 -p 8000 inventory.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    environment:
      DJANGO_ENV: dev
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A inventory worker -l info
    volumes:
      - .:/app
    env_file:
      - .env.dev
    environment:
      DJANGO_ENV: dev
      DJANGO_SETTINGS_MODULE: inventory.settings
    depends_on:
      - redis
      - web

  celery_beat:
    build: .
    container_name: inventory_celery_beat
    command: celery -A inventory beat -l info
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - redis
      - web
  db:
    image: postgres:15
    container_name: inventory_db
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${DB_NAME:-inventory}
      POSTGRES_USER: ${DB_USER:-inventory}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-inventory}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: inventory_nginx
    ports:
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./localhost+2.crt:/etc/nginx/certs/localhost.crt:ro
      - ./localhost+2.key:/etc/nginx/certs/localhost.key:ro
    depends_on:
      - web

volumes:
  postgres_data:
